name = "gl_dfjson"
version = "0.0.1-alpha"

description = "A collection of DFJson types, encoders, and decoders for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "DynamicCake", repo = "gleam-dfjson" }
links = [{ title = "Main docs", href = "https://dftools.dev/dfjson" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
